name: Deploy to staging.cypruseats.com

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        erver: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME_STAGING }}
        password: ${{ secrets.FTP_PASSWORD }}
